[package]
name = "perfrecord"
version = "0.1.0"
authors = ["Markus Stange <mstange@themasta.com>"]
edition = "2018"
license = "MIT/Apache-2.0"

[dependencies]
mach-ipc-rendezvous = { path = "../mach-ipc-rendezvous" }
objc = "0.2.7"
cocoa = "0.20.1"
uuid = "0.8.1"
libc = "0.2.70"
which = "3.1.1"
serde_json = "1.0.53"
mach = "0.3.2"

[profile.release]
debug = true
