[package]
name = "query-api"
version = "0.1.0"
authors = ["Markus Stange <mstange@themasta.com>"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
samply-api = { path = "../../../samply-api" }
structopt = "0.3.14"
memmap2 = "0.5.0"
anyhow = "1.0.28"
futures = "0.3.5"
serde_json = "1.0.68"
