[package]
name = "samply"
version = "0.8.0"
authors = ["Markus Stange <mstange@themasta.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "A macOS command line profiler."
repository = "https://github.com/mstange/samply/"
readme = "Readme.md"

[dependencies]
perfrecord-mach-ipc-rendezvous = { version = "0.2.1", path = "../perfrecord-mach-ipc-rendezvous" }

# profiler-symbol-server = { path = "../../profiler-symbol-server" }
profiler-symbol-server = "0.12.0"

profiler-get-symbols = "0.14.0"

# fxprof-processed-profile = { path = "../fxprof_processed_profile" }
fxprof-processed-profile = "0.1.0"

tokio = { version = "1.17.0", features = ["rt", "rt-multi-thread", "macros"] }
uuid = "1.0.0"
libc = "0.2.71"
mach = "0.3.2"
tempfile = "3.1.0"
structopt = "0.3.14"
thiserror = "1.0.19"
crossbeam-channel = "0.5.4"
signal-hook = "0.3.9"
serde_json = "1.0.53"
memmap2 = "0.5.3"
object = "0.28.3"

# framehop = { path = "../../framehop" }
framehop = "0.6.0"
flate2 = "1.0.23"

[profile.release]
debug = true
panic = "abort"
