[package]
name = "samply"
version = "0.8.0"
authors = ["Markus Stange <mstange@themasta.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "A macOS command line profiler."
repository = "https://github.com/mstange/samply/"
readme = "README.md"

[dependencies]

tokio = { version = "1.17.0", features = ["rt", "rt-multi-thread", "macros"] }
samply-server = { version = "0.14", path = "../samply-server" }
structopt = "0.3.14"

[target.'cfg(target_os = "macos")'.dependencies]

perfrecord-mach-ipc-rendezvous = { version = "0.2.1", path = "../perfrecord-mach-ipc-rendezvous" }
samply-symbols = { version = "0.17", path = "../samply-symbols" }
# fxprof-processed-profile = { path = "../fxprof-processed-profile" }
fxprof-processed-profile = "0.1.0"
# framehop = { path = "../../framehop" }
framehop = "0.7"

uuid = "1.0.0"
libc = "0.2.71"
mach = "0.3.2"
tempfile = "3.1.0"
thiserror = "1.0.19"
crossbeam-channel = "0.5.4"
signal-hook = "0.3.9"
serde_json = "1.0.53"
memmap2 = "0.5.3"
object = "0.29"
flate2 = "1.0.23"

[profile.release]
debug = true
panic = "abort"
