[package]
name = "linux-perf-data"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
byteorder = "1.4.3"
debugid = "0.8.0"
framehop = "0.7.0"
# framehop = { path = "../framehop" }
futures = "0.3.21"
memchr = "2.4.1"
memmap2 = "0.5.3"
object = "0.28.3"
profiler-get-symbols = "0.14.0"
# profiler-get-symbols = { path = "../profiler-get-symbols/lib" }
thiserror = "1.0.30"

[profile.release]
debug = true
