[package]
name = "profiler-symbol-server"
version = "0.5.0"
authors = ["Markus Stange <mstange@themasta.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "A local webserver that lets the Firefox profiler obtain symbol information."
homepage = "https://github.com/mstange/profiler-symbol-server/"
repository = "https://github.com/mstange/profiler-symbol-server/"
readme = "README.md"

[dependencies]
hyper = { version = "0.14.8", features = ["full"] }
tokio = { version = "1.6.1", features = ["full"] }
futures = "0.3"
profiler-get-symbols = { version = "0.2.2", features = ["send_futures"] }
memmap2 = "0.2.3"
serde_json = "1.0.53"
uuid = "0.8.2"
structopt = "0.3.14"
percent-encoding = "2.1.0"
failure = "0.1.8"
object = "0.25.0"
libc = "0.2.71"
core-foundation-sys = "0.8.2"
core-foundation = "0.9.1"
flate2 = "1.0"
webbrowser = "0.5.5"
