[workspace]
members = [
  "lib",
  "wasm",
  "examples/dump_table",
  "examples/query_api",
  "examples/benchmarks"
]
default-members = [
  "lib",
  "wasm"
]

[profile.release]
lto = true
debug = true
