[package]
name = "samply-api"
version = "0.16.1"
authors = ["Markus Stange <mstange@themasta.com>"]
license = "MIT/Apache-2.0"
edition = "2018"
description = "Symbolication utilities for the Firefox profiler."
homepage = "https://github.com/mstange/profiler-get-symbols/"
repository = "https://github.com/mstange/profiler-get-symbols/"
readme = "README.md"

[features]
default = []
send_futures = []

[dependencies]
samply-symbols = { path = "../samply-symbols" }
thiserror = "1.0.26"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
serde-hex = "0.1.0"

[dev-dependencies]
memmap2 = "0.5.0"
anyhow = "1.0.28"
futures = "0.3.5"
assert-json-diff = "2.0.1"
serde_json = "1.0.68"
